title: "시선의방"
email: kln99988@naver.com
timezone: Asia/Seoul
baseurl: "https://park-yina.github.io/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: kr
lang: kr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: park-yina
    display_name: 괭시니
    avatar: 'assets/images/sal.png'
    email: kln99988@naver.com
    description: "예술대학과 예술고등학교를 졸업한 참신한 개발자입니다."
 

# Social
social:
  instagram: https://www.instagram.com/meow_yina/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives